namespace WitchMendokusai
{
	public enum GameStatType
	{
		TOTAL_MONSTER_KILL = 0,
		TOTAL_BOSS_KILL = 1,

		TOTAL_DUNGEON_CLEAR = 99,
		TOTAL_DUNGEON_TIME = 100,

		NYANG = 1000,
		MANA = 1100,

		VILLAGE_QUEST_EXP = 2000,
		VILLAGE_QUEST_EXP_MAX = 2001,
		VILLAGE_QUEST_LEVEL = 2002,

		VILLAGE_REPUTATION_EXP = 2100,
		VILLAGE_REPUTATION_EXP_MAX = 2101,
		VILLAGE_REPUTATION_LEVEL = 2102,

		// 임시
		POT_COUNT = 3000, // 솥 개수 (솥 시너지)
	}
}